
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[504] =
    {   0,
        0,    0,   54,   52,   51,    1,   52,   47,   44,   49,
       49,   49,   49,   49,   49,   49,   49,   43,   49,   49,
       49,   49,   49,   49,   42,   44,   52,   52,   52,   52,
       52,   52,   52,   52,   43,   52,   52,   52,   52,   52,
       52,   42,   51,    0,   50,   47,   49,    0,    0,    0,
        0,    0,    0,    0,   21,    0,    0,    0,   23,   22,
        0,   23,   23,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   21,    0,    0,    0,   23,   22,    0,   23,   23,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   27,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   23,    0,    0,    0,
       29,   26,    0,    0,    0,    0,    0,    0,    0,    0,
       30,    0,   48,    0,    0,    0,    0,    0,   27,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   23,    0,
        0,    0,   29,   26,    0,    0,    0,    0,    0,    0,
        0,    0,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   18,
       18,    0,    0,    0,   20,    0,    0,   28,   15,   15,
       11,    0,    0,    0,    0,    0,    9,    0,   19,   19,
        0,    0,    0,    0,    0,    0,    0,    0,   25,   35,
        0,    0,    0,    0,   18,   18,    0,    0,    0,   20,
        0,    0,   28,   15,   15,   11,    0,    0,    0,    0,
        0,    9,    0,   19,   19,    0,    0,    0,    0,    0,
       25,   35,    0,    2,    0,    0,    0,    0,    4,    0,

       14,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   25,    0,    2,    0,    0,    0,    0,
       14,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   25,
        0,    2,    0,    0,    0,    0,    0,    0,   17,   17,
        3,    3,    0,    0,    0,    9,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    2,    0,    0,    0,
        0,    0,   17,   17,    3,    3,    0,    0,    0,    9,
        0,    0,   16,    0,    0,    0,    0,    0,   10,   10,

        0,    0,   33,    0,    0,   13,    0,    0,    8,    8,
        5,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,   10,    0,    0,   33,    0,    0,   13,    0,
        8,    8,    5,    5,    0,    0,   12,   12,    0,    0,
        0,   34,    6,    0,    0,   13,    0,   24,    0,   38,
       36,   39,    0,   12,   12,    0,    0,   34,    6,    0,
        0,   13,   24,    0,   45,   31,    0,   34,   46,    0,
        0,    0,    7,    7,   31,    0,   34,    7,    7,   31,
       32,    0,    0,    0,   31,   32,   32,    0,    0,    0,
       32,   41,    0,    0,    0,    0,    0,    0,    0,    0,

       37,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,   10,   11,
       11,   11,   12,   11,   11,   13,   14,   11,   15,   16,
       17,   18,   19,   20,   21,   11,   11,   11,   22,   11,
        1,    1,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   31,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   31,   31,
       45,   46,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   47,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   48,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    3,    4,    4,    5,    4,    4,    4,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        5,    4,    4,    4,    4,    4,    1,    6
    } ;

static const flex_int16_t yy_base[508] =
    {   0,
        0,    0, 1054, 1055, 1051, 1055, 1048, 1046,   23,   24,
       31,   30,   39, 1013,   15,   32, 1012,   45, 1011,   20,
       46,   49,   50,   23, 1010,   58,   56,   66,   68,   74,
       69,   71,   88,   72,   90,   95,   98,  100,  101,  103,
      103,   79, 1044, 1041, 1055, 1039, 1006, 1000, 1001, 1014,
      992,  998, 1002, 1000,  994,  104,  998, 1001,  122, 1055,
      111,  991,  990, 1003,  987, 1001,  987,  127,  130,  110,
      990,  998,  133,    0,  114,  135,  124,  144,  140,  146,
      148,  145,  150,  151,  153,  172,  155,  166,  172,  174,
      179,  182,  189,  188,  189,  208,  195,  187,  218,  218,

      981,  147,  995,  998,  981,  995,  978,  206,  990,  975,
      989,  973,  218,  979,  985,  972, 1055,  979,  982,  981,
     1055, 1055,  966,  964,  974,  210, 1003,  976,  973,  965,
     1055,  961,    0,  216,  226,  229,  235,  237,  238,  244,
      240,  242,  249,  257,  268,  258,  259,  255,  266,  277,
      285,  287,  271,  273,  281,  279,  288,  289,  315,  311,
      301,  305,  295,  307,  976,  969,  960,  961,  969,  316,
      963,  951,  965,  964,  951,  958,  961,  317,  318,  964,
      955,  946,  948,  955,  947,  946,  324,  943,  939,  935,
      950,  349,  951,  952,  934,  334,  331,  337,  341,  342,

      339,  345,  344,  346,  355,  368,  373,  374,  376,  382,
      386,  384,  388,  391,  387,  392,  403,  406,  414,  394,
      418,  422,  426,  420,  940,  356,  428,  946,  435,  932,
     1055,  429,  937,  934, 1055,  941,  932, 1055,  927, 1055,
     1055,  926,  929,  922,  936,  930,  430,  441,  921, 1055,
      932,  917,  934,  913,  924,  925,  447,  928,  917, 1055,
      449,  453,  456,  455,  441,  450,  462,  465,  464,  468,
      479,  469,  470,  471,  472,  483,  485,  486,  498,  501,
      491,  507,  519,  513,  503,  522,  506,  533,  515,  518,
      529,  535,  920,  911,  922,  558,  947,  920, 1055,  907,

      906, 1055,  903,  917,  907,  900,  540,  545,  898,  347,
      900,  915,  560,  936,  897,  896,  895,  547,  905,  890,
      887,  895,  898,  893,  553,  549,  551,  580,  582,  563,
      564,  565,  567,  569,  570,  579,  601,  608,  571,  600,
      593,  611,  620,  635,  615,  617,  621,  622,  619,  630,
      626, 1055,  381,  892,  647,  899,  884,  888,  884, 1055,
      883, 1055,  628,  898,  878,  550,  660,  649,  652, 1055,
      892,  895,  881,  880,  879,  656,  658,  661,  662,  664,
      665,  668,  671,  670,  677,  672,  698,  691,  680,  699,
      707,  708,  678,  711,  887,  890,  876,  870,  871, 1055,

      874,  881, 1055,  705,  882,  867,  878,  866,  855, 1055,
      854, 1055,  844,  844,  848,  841,  838,  839,  715,  718,
      726,  727,  728,  729,  730,  731,  732,  747,  748,  733,
      749,  734,  760,  739,  757,  763, 1055,  834,  830,  835,
      811,  808, 1055,  806,  821, 1055,  799, 1055,  809, 1055,
      823,  817,  766,  761,  762,  778,  770,  780,  768,  784,
      790,  769,  781,  799, 1055,  806,  680,  655, 1055,  611,
      410,  662,  570, 1055,  808,  792,  810,  812,  807,  826,
      829,  566,  605,  593,    0,  831,  841,  504,  483,  401,
      844, 1055,  326,  243,  197,  182,  158,  118,   64,   46,

     1055, 1055, 1055,  886,  891,  895,  900
    } ;

static const flex_int16_t yy_def[508] =
    {   0,
      503,    1,  503,  503,  503,  503,  504,  503,  505,  505,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,   29,
      506,  506,  503,  504,  503,  503,   10,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  507,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,   29,  506,  506,  506,  506,
      506,  506,  506,  506,   29,  506,  506,  506,  506,   29,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  507,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,   29,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,   29,  506,  506,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  506,  506,
      506,  506,  506,  506,  506,  506,   29,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  506,  506,  506,  506,  506,  503,
      503,  503,  503,  503,  475,  475,  503,  503,  503,  503,
      475,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,    0,  503,  503,  503,  503
    } ;

static const flex_int16_t yy_nxt[1104] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,    4,   26,   27,   28,   29,   30,   31,   31,
       31,   32,   31,   33,   34,   31,   35,   36,   37,   38,
       39,   40,   41,   31,   42,   31,    4,    4,   48,  503,
       61,  503,   49,  503,   53,   62,  503,   55,   73,  503,
       52,   56,   68,   50,  503,   58,   57,   54,   63,   65,
       51,  503,   59,   69,   60,  503,   70,   71,   74,  502,
       74,  503,  503,   76,   66,  503,   72,   77,   74,   80,
       74,   74,   79,   74,   74,   82,   74,  501,   78,   83,

       85,   74,   81,  503,   84,   51,   88,   86,   91,   87,
       74,   89,   74,  503,   92,  503,  503,   74,  503,  503,
       74,  503,   74,   74,   90,   74,  503,   96,   97,   93,
       98,   94,  109,  127,   75,  503,   74,  503,  100,   99,
       95,  500,  503,  128,  110,  503,   74,  503,  503,  113,
      503,  115,  116,  114,  122,  124,  131,   74,  123,  125,
      131,  503,   74,  135,  132,  126,   74,   74,   74,  136,
       74,  503,   74,   74,  166,   74,  134,   74,  141,  137,
      138,  499,  503,  139,  144,  140,  143,  503,   74,  167,
      142,  503,  503,  503,   74,  503,   74,  503,  503,  145,

      503,   74,  503,  146,   74,  150,  147,  148,   75,   74,
       74,   74,  149,  503,  149,  152,  154,   74,  159,  503,
      155,  503,  161,  151,  498,   75,  503,  153,  160,  503,
       74,  173,  174,  156,  503,  503,  503,  157,   74,  497,
       74,  163,  503,  158,  162,  163,  190,  179,   74,  164,
      180,   74,  191,  197,   75,  503,  199,   74,  196,   74,
       74,  201,   74,  503,   74,  503,   74,  205,  198,  203,
      204,   74,  496,  503,  200,  207,  503,   74,  202,   74,
       74,   74,  503,  206,  503,  503,  212,  503,   74,  503,
       74,  503,  211,   74,  213,   74,  503,  209,  208,   74,

      210,   74,  503,   74,  503,  503,  503,   74,  214,   74,
       74,   74,  215,  503,  216,  503,  192,   74,  503,  219,
      503,  218,  217,   74,  503,  220,  503,   74,  503,   74,
      223,  221,  503,   74,  503,  503,  503,   74,  222,  230,
      239,  224,  503,  231,  240,  241,  163,  249,  503,  242,
      192,  250,  503,   74,  503,  495,   74,  261,  503,   74,
      262,   74,  503,   74,   74,  265,   74,   74,   74,  266,
      267,  269,  364,  270,  263,  255,  264,   74,  503,  294,
      256,  503,  353,  257,  503,  365,  503,  268,  503,  503,
       74,  503,  503,  503,  271,   74,   74,  274,  295,  272,

      273,  275,  503,  276,   74,  276,   74,  277,   74,   74,
       74,  471,   75,   74,   74,  503,   74,  278,  397,  281,
      503,  503,  282,  279,  280,   74,  284,  283,   74,  503,
      285,  503,  494,  503,  503,  503,   74,  288,  503,  503,
       74,  503,   74,  286,   74,  289,  483,  290,   74,  291,
      503,  296,  301,  503,  287,  297,  302,  311,  299,  312,
      292,  503,  299,   74,  313,  503,  300,  503,  314,  503,
      321,   74,   74,  503,  322,   74,  326,   74,   74,  328,
      266,  330,  325,  329,   74,  331,   74,   74,  503,  332,
       74,   74,   74,   74,   74,  327,  503,  503,  333,  334,

      503,   74,  503,  503,  336,   74,  335,   74,   74,  503,
      275,  503,  503,   74,  493,  503,  503,  503,  503,  503,
       74,  337,  340,   74,  276,   74,  503,  339,   74,   74,
      503,  492,  503,  503,  341,   74,  342,   74,  503,  338,
       74,   74,  343,  349,   74,  503,  344,  346,  503,  345,
      503,   74,  285,  503,  503,   74,  347,   74,  348,  353,
      503,  367,  503,  359,  350,  503,  503,  360,  361,  503,
      370,   74,  362,   74,  370,   74,  503,  311,  377,  312,
      503,  353,  503,  353,  376,   74,   74,   74,  377,   74,
      378,   74,   74,   74,  490,  380,  503,  297,  503,  314,

      503,   74,   74,  332,   74,  381,  489,  488,  379,  474,
      503,  503,  503,  387,  503,   74,  503,  503,  503,  329,
      382,  367,   74,   74,  383,  388,  503,  503,  384,  503,
       74,  385,  390,   74,  390,  386,  367,   74,  389,   74,
      503,   74,   74,   74,   74,  393,  482,  503,  503,  393,
      394,  395,   74,  404,  391,  503,  392,   74,  503,  344,
      393,  367,  503,  472,  503,  350,  503,  503,  503,  503,
      399,  396,  409,  405,  400,  411,  410,  503,   74,  412,
       74,  419,  503,   74,   74,  422,   74,   74,  413,  423,
       74,  424,   74,   74,   74,  468,  421,  408,  484,   74,

       74,  420,   74,  503,  426,  503,  425,  481,  503,  503,
      384,  503,  503,   74,  429,  503,  386,  503,  503,  503,
       74,   74,  430,  427,  503,  503,  341,  503,  342,   74,
      431,  433,  443,   74,  432,  434,  444,   74,  503,   75,
       74,  455,  454,  428,  435,  503,  503,  436,   74,   74,
       74,   74,   74,   74,  503,   74,   74,  458,  503,  459,
      462,   74,  503,  460,  457,  503,  423,  456,   75,   74,
       74,   74,  461,  503,  503,  503,  503,  503,  503,   74,
      503,  503,   74,   74,   74,   74,  503,  462,  432,  473,
       74,   74,   74,  474,  503,  503,  503,  463,  464,  434,

       74,  454,   74,   74,  503,  475,   74,  503,  503,  503,
      503,  476,   74,  459,   74,  503,  503,  503,  472,  486,
      477,   74,  478,  459,  471,  503,  479,  503,  503,   74,
       74,  503,   74,  480,   74,  485,  470,  503,  469,  503,
      480,  480,  485,  485,  443,  443,  503,  480,  468,  485,
      477,  479,  467,  480,  503,  503,  487,  503,  491,  503,
      480,  480,  466,  487,  487,  491,  491,  480,  487,  465,
      487,  491,  491,  437,  453,  487,  487,  452,  491,  491,
      451,  450,  487,  449,  448,  491,   44,   44,   44,   44,
       44,   44,   47,  412,  410,   47,   47,   75,   75,   75,

       75,  133,  447,  133,  133,  446,  446,  445,  442,  441,
      400,  440,  439,  438,  437,  418,  417,  416,  415,  414,
      407,  406,  362,  360,  403,  402,  401,  398,  324,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  366,
      363,  358,  357,  356,  355,  302,  299,  354,  353,  352,
      352,  351,  324,  323,  320,  319,  318,  317,  316,  315,
      250,  310,  309,  308,  307,  241,  240,  306,  305,  304,
      303,  231,  298,  293,  260,  259,  258,  254,  253,  252,
      251,  248,  247,  246,  245,  244,  243,  241,  238,  237,
      236,  235,  234,  233,  232,  229,  228,  227,  226,  225,

      131,  195,  194,  193,  192,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  178,  177,  176,  175,  172,  171,
      170,  169,  168,  165,  130,  129,  121,  120,  119,  118,
      117,  117,  112,  111,  108,  107,  106,  105,  104,  103,
      102,  101,  503,   46,   45,   43,  503,   67,   64,  503,
       46,   45,   43,  503,    3,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503
    } ;

static const flex_int16_t yy_chk[1104] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,   10,
       15,   15,    9,   10,   11,   16,   20,   12,   24,   24,
       10,   12,   20,    9,   10,   13,   12,   11,   16,   18,
        9,   10,   13,   21,   13,   13,   22,   23,   27,  500,
       26,   18,   21,   26,   18,   22,   23,   26,   28,   28,
       29,   31,   27,   32,   34,   29,   30,  499,   26,   29,

       30,   42,   28,   27,   29,   26,   32,   30,   34,   30,
       33,   33,   35,   28,   35,   29,   31,   36,   32,   34,
       37,   30,   38,   39,   33,   41,   42,   38,   39,   35,
       40,   36,   56,   70,   40,   33,   75,   35,   41,   40,
       37,  498,   36,   70,   56,   37,   77,   38,   39,   59,
       41,   61,   61,   59,   68,   69,   73,   76,   68,   69,
       73,   75,   79,   77,   73,   69,   78,   82,   80,   78,
       81,   77,   83,   84,  102,   85,   76,   87,   83,   79,
       80,  497,   76,   81,   85,   82,   84,   79,   88,  102,
       83,   78,   82,   80,   89,   81,   90,   83,   84,   86,

       85,   91,   87,   86,   92,   91,   88,   88,   86,   98,
       94,   93,   89,   88,   90,   93,   95,   97,   97,   89,
       95,   90,   98,   92,  496,   95,   91,   94,   97,   92,
       96,  108,  108,   96,   98,   94,   93,   96,  134,  495,
       99,  100,   97,   96,   99,  100,  126,  113,  135,  100,
      113,  136,  126,  135,  100,   96,  136,  137,  134,  138,
      139,  138,  141,  134,  142,   99,  140,  141,  135,  140,
      140,  143,  494,  135,  137,  143,  136,  148,  139,  144,
      146,  147,  137,  142,  138,  139,  147,  141,  149,  142,
      145,  140,  146,  153,  148,  154,  143,  145,  144,  150,

      145,  156,  148,  155,  144,  146,  147,  151,  150,  152,
      157,  158,  151,  149,  152,  145,  159,  163,  153,  157,
      154,  156,  155,  161,  150,  158,  156,  162,  155,  164,
      161,  158,  151,  160,  152,  157,  158,  159,  160,  170,
      178,  162,  163,  170,  178,  179,  164,  187,  161,  179,
      192,  187,  162,  197,  164,  493,  196,  196,  160,  198,
      197,  201,  159,  199,  200,  200,  203,  202,  204,  200,
      201,  203,  310,  204,  198,  192,  199,  205,  197,  226,
      192,  196,  353,  192,  198,  310,  201,  202,  199,  200,
      206,  203,  202,  204,  205,  207,  208,  208,  226,  206,

      207,  208,  205,  209,  210,  210,  212,  209,  211,  215,
      213,  471,  209,  214,  216,  206,  220,  211,  353,  214,
      207,  208,  215,  212,  213,  217,  217,  216,  218,  210,
      217,  212,  490,  211,  215,  213,  219,  220,  214,  216,
      221,  220,  224,  218,  222,  221,  471,  222,  223,  223,
      217,  227,  232,  218,  219,  227,  232,  247,  229,  247,
      224,  219,  229,  265,  248,  221,  229,  224,  248,  222,
      257,  261,  266,  223,  257,  262,  262,  264,  263,  263,
      265,  264,  261,  263,  267,  267,  269,  268,  265,  267,
      270,  272,  273,  274,  275,  262,  261,  266,  268,  269,

      262,  271,  264,  263,  272,  276,  271,  277,  278,  267,
      274,  269,  268,  281,  489,  270,  272,  273,  274,  275,
      279,  278,  281,  280,  277,  285,  271,  280,  287,  282,
      276,  488,  277,  278,  282,  284,  282,  289,  281,  279,
      290,  283,  283,  290,  286,  279,  283,  287,  280,  286,
      285,  291,  284,  287,  282,  288,  288,  292,  289,  296,
      284,  313,  289,  307,  291,  290,  283,  307,  308,  286,
      318,  326,  308,  327,  318,  325,  291,  366,  327,  366,
      288,  328,  292,  329,  325,  330,  331,  332,  326,  333,
      330,  334,  335,  339,  484,  334,  326,  296,  327,  313,

      325,  336,  328,  331,  329,  335,  483,  482,  333,  473,
      330,  331,  332,  339,  333,  341,  334,  335,  339,  328,
      336,  343,  340,  337,  337,  340,  336,  328,  337,  329,
      338,  338,  341,  342,  342,  338,  344,  345,  340,  346,
      341,  349,  343,  347,  348,  348,  470,  340,  337,  348,
      349,  351,  350,  363,  345,  338,  346,  344,  342,  343,
      347,  367,  345,  472,  346,  350,  349,  343,  347,  348,
      355,  351,  368,  363,  355,  369,  368,  350,  376,  369,
      377,  376,  344,  378,  379,  379,  380,  381,  369,  379,
      382,  380,  384,  383,  386,  468,  378,  367,  472,  385,

      393,  376,  389,  376,  382,  377,  381,  467,  378,  379,
      383,  380,  381,  388,  388,  382,  385,  384,  383,  386,
      387,  390,  389,  387,  385,  393,  390,  389,  390,  391,
      391,  392,  404,  394,  391,  392,  404,  419,  388,  392,
      420,  420,  419,  387,  392,  387,  390,  394,  421,  422,
      423,  424,  425,  426,  391,  430,  432,  425,  394,  427,
      430,  434,  419,  427,  424,  420,  422,  421,  427,  428,
      429,  431,  428,  421,  422,  423,  424,  425,  426,  435,
      430,  432,  433,  454,  455,  436,  434,  429,  431,  453,
      459,  462,  457,  453,  428,  429,  431,  435,  436,  433,

      456,  455,  458,  463,  435,  456,  460,  433,  454,  455,
      436,  457,  461,  461,  476,  459,  462,  457,  452,  476,
      458,  464,  464,  460,  451,  456,  464,  458,  463,  479,
      475,  460,  477,  466,  478,  475,  449,  461,  447,  476,
      466,  466,  475,  475,  445,  444,  464,  466,  442,  475,
      477,  478,  441,  480,  479,  475,  481,  477,  486,  478,
      480,  480,  440,  481,  481,  486,  486,  480,  487,  439,
      481,  491,  486,  438,  418,  487,  487,  417,  491,  491,
      416,  415,  487,  414,  413,  491,  504,  504,  504,  504,
      504,  504,  505,  411,  409,  505,  505,  506,  506,  506,

      506,  507,  408,  507,  507,  407,  406,  405,  402,  401,
      399,  398,  397,  396,  395,  375,  374,  373,  372,  371,
      365,  364,  361,  359,  358,  357,  356,  354,  324,  323,
      322,  321,  320,  319,  317,  316,  315,  314,  312,  311,
      309,  306,  305,  304,  303,  301,  300,  298,  297,  295,
      294,  293,  259,  258,  256,  255,  254,  253,  252,  251,
      249,  246,  245,  244,  243,  242,  239,  237,  236,  234,
      233,  230,  228,  225,  195,  194,  193,  191,  190,  189,
      188,  186,  185,  184,  183,  182,  181,  180,  177,  176,
      175,  174,  173,  172,  171,  169,  168,  167,  166,  165,

      132,  130,  129,  128,  127,  125,  124,  123,  120,  119,
      118,  116,  115,  114,  112,  111,  110,  109,  107,  106,
      105,  104,  103,  101,   72,   71,   67,   66,   65,   64,
       63,   62,   58,   57,   55,   54,   53,   52,   51,   50,
       49,   48,   47,   46,   44,   43,   25,   19,   17,   14,
        8,    7,    5,    3,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical.l"
/** Seccion de definiciones **/
#line 3 "lexical.l"
#include "syntactical.tab.h"

#line 856 "lex.yy.c"
/** Seccion de reglas **/
#line 858 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 14 "lexical.l"


#line 1078 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 504 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1055 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "lexical.l"
{return ENDLINE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lexical.l"
{return INSERT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lexical.l"
{return INSERT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lexical.l"
{return INSERT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lexical.l"
{return INSERT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lexical.l"
{return INSERT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lexical.l"
{return SELECT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lexical.l"
{return SELECT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lexical.l"
{return SELECT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lexical.l"
{return SELECT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lexical.l"
{return SELECT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lexical.l"
{return UPDATE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lexical.l"
{return SET;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lexical.l"
{return SET;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lexical.l"
{return SET;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lexical.l"
{return SET;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lexical.l"
{return DELETE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lexical.l"
{return DELETE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lexical.l"
{return DELETE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lexical.l"
{return FROM;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lexical.l"
{return FROM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lexical.l"
{return INTO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lexical.l"
{return THE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lexical.l"
{return ROWS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lexical.l"
{return HAVE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lexical.l"
{return THAT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lexical.l"
{return WITH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lexical.l"
{return WHERE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lexical.l"
{return BY;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lexical.l"
{return JOIN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lexical.l"
{return ASC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lexical.l"
{return DESC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lexical.l"
{return DISTINCT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lexical.l"
{return DISTINCT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 50 "lexical.l"
{return ALL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 51 "lexical.l"
{return GREATER;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 52 "lexical.l"
{return GREATEREQUAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 53 "lexical.l"
{return EQUAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lexical.l"
{return LESS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lexical.l"
{return LESSEQUAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lexical.l"
{return DIFERENT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lexical.l"
{return AND;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lexical.l"
{return OR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lexical.l"
{return TO;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lexical.l"
{return GROUP_BY;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lexical.l"
{return ORDER_BY;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lexical.l"
{yylval.num = atoi(yytext); return NUMBER;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lexical.l"
{yylval.str = strdup(yytext); return FIELD;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lexical.l"
{yylval.str = strdup(yytext); return TABLE;}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 65 "lexical.l"
{yylval.str = strdup(yytext); return VALUE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lexical.l"
{/** Ignorar espacios **/}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lexical.l"
{printf("Error lexico, categoria no reconocida: %s.\n", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 69 "lexical.l"
ECHO;
	YY_BREAK
#line 1402 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 504 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 504 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 503);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 69 "lexical.l"


/** Seccion de codigo de usuario **/

int yywrap(){
	return 1;
}

